### ISSUE TITLE
LessChromeHD: no longer works with Firefox 35.0

### ISSUE THREAD

**Issue by GolgothBe** [mozilla/prospector#677]
LessChrome HD 8 is always available in the Firefox Add-ons and installable, but nothing happens with the latest version of Firefox 35.0 (tested on Windows 7 and Linux)...

**Comment by futtta** [comment]
same here, also [confirmed in latest reviews](https://addons.mozilla.org/en-US/firefox/addon/prospector-lesschrome-hd/reviews/)

:+1:  for a fix :-)

**Comment by futtta** [comment]
OK, so error thrown is:
`(process:9020): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
1421746006699	
addons.xpi	WARN	Error loading bootstrap.js for lessChrome.HD@prospector.labs.mozilla: TypeError: redeclaration of variable event (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/frank/.mozilla/firefox/jy6bws91.default/extensions/lessChrome.HD@prospector.labs.mozilla.xpi!/bootstrap.js:226:8) 
JS Stack trace: @XPIProvider.jsm:4333:1 < XPI_loadBootstrapScope@XPIProvider.jsm:4333:7 < XPI_callBootstrapMethod@XPIProvider.jsm:4408:1 < XPI_startup@XPIProvider.jsm:2159:13 < callProvider@AddonManager.jsm:208:12 < _startProvider@AddonManager.jsm:667:5 < AMI_startup@AddonManager.jsm:824:9 < AMP_startup@AddonManager.jsm:2402:5 < AMC_observe@addonManager.js:55:7
1421746006702
addons.xpi	WARN	Add-on lessChrome.HD@prospector.labs.mozilla is missing bootstrap method startup`

The fix: in boostrap.js on line 226-228 replace event (which as the error states was indeed already declared on line 210) with shownEvent:

`
let shownEvent = document.createEvent("Event");
shownEvent.initEvent("LessChromeShown", true, false);
trigger.dispatchEvent(shownEvent);
`

This fixes LessChromeHD (which is indepensable on my small-screen netbook, really) for me.
