### ISSUE TITLE
LessChromeHD: Enable e10s support.

### ISSUE THREAD

**Issue by hbayindir** [mozilla/prospector#686]
Less chrome HD is a very useful add-on, but lacks e10s support. Will it be implemented or what it takes to implement e10s support to LessChrome?

**Comment by Mardak** [comment]
Looks unlikely this add-on will be updated as Firefox 57 will only support WebExtensions.
https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/
