### ISSUE TITLE
Why was this discontinued?

### ISSUE THREAD

**Issue by Ander3232** [mozilla/prospector#688]
What a great and useful extension—it adds a good 1/4" of vertical real estate on a laptop screen by hiding FF's address bar until you hover over it.

Why was it discontinued? I'm using the newest FF at this writing (53.0.3), and LessChrome HD is working fine. I wanted to point a friend to its install page, and was quite surprised to find it had been removed.

**Comment by Mardak** [comment]
It looks like the add-on was disabled by administrator. Not sure why as of right now:
https://addons.mozilla.org/en-US/firefox/addon/prospector-lesschrome-hd/

**Comment by Ander3232** [comment]
Too bad. I understand the idea of conforming to standards, but this is, like, the 5th time that a [i]new[/i] set of standards has been imposed on FF extension developers... Where does it end? And why not allow some tried-and-true extensions to continue to function? (I know, "voice in the wilderness...")

With the preponderance of mobile devices, the ability to auto-hide the address bar is so useful, it should be a standard FF option. Till that happens, this extension is all we have. Seems like this issue needs a bit more imagination.
